spring:
  config:
    import: "optional:file:.env.uat[.properties]"
  datasource:
    url: ${FORUM_UAT_DB_URL}
    username: ${FORUM_UAT_DB_USERNAME}
    password: ${FORUM_UAT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

forum:
  security:
    jwt:
      secret: ${FORUM_UAT_JWT_SECRET}
