spring:
  config:
    import: "optional:file:.env.prod[.properties]"
  datasource:
    url: ${FORUM_PROD_DB_URL}
    username: ${FORUM_PROD_DB_USERNAME}
    password: ${FORUM_PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

forum:
  security:
    jwt:
      secret: ${FORUM_PROD_JWT_SECRET}
